# Generated by Django 4.0.1 on 2022-03-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Postlar'},
        ),
        migrations.AlterField(
            model_name='post',
            name='sarlavha',
            field=models.CharField(max_length=20),
        ),
    ]
