# Generated by Django 4.0.1 on 2022-03-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_options_alter_post_sarlavha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sarlavha',
            field=models.CharField(max_length=50),
        ),
    ]
